Update makepattern.py for python3 and modern nxo64
TSRBerry/nxo-utils pull request #1
Opened 2024-10-05 17:42 UTC by averne

2024-10-05 17:46 UTC, averne commented
Ok it's broken, will reopen once it works

2024-10-05 17:59 UTC, averne commented
Well it was actually working, I was looking at the wrong file... Sorry about that

2024-10-07 20:38 UTC, TSRBerry requested changes
Thank you very much, I haven't worked on this in quite some time!

As a test I ran the old version (with python2) against the ACNH sdk of the base game and compared the output with the new version (with python3 and 2).

I noticed the output is a lot smaller when using python3. It still contains everything, but the regexes (?) look a lot better.

Is your `applypattern-ghidra.py` script able to handle these as well?

2024-10-07 20:38 UTC, TSRBerry commented on pattern/makepattern.py
>  			positions = [m.start() for m in re.finditer(regex, textstr)]
With these changes python2 is stuck at this line.
I waited for ~12 minutes and the output file was still empty, so I stopped the script there.

2024-10-07 20:38 UTC, TSRBerry commented on pattern/makepattern.py
> +			regex = b''.join((re.escape(i.to_bytes(1)) if m == 0xff else b'[\0-\xff]') for i, m in zip(bits, mask_str))
I wasn't able to find a way that works for both py2 and 3 without issues, so let's just use the old version for py2 and the new version for py3:

```suggestion
			if sys.version_info[0] > 2:
			    mask_str = b''.join(struct.pack('<I', m) for m in mask)
				bits = b''.join(struct.pack('<I', i & m) for i, m in zip(instrs, mask))
				regex = b''.join((re.escape(i.to_bytes(1)) if m == 0xff else b'[\0-\xff]') for i, m in zip(bits, mask_str))
			else:
				mask_str = ''.join(struct.pack('<I', m) for m in mask)
				bits = ''.join(struct.pack('<I', i & m) for i, m in zip(instrs, mask))
				regex = ''.join((re.escape(i) if m == '\xFF' else r'[\0-\xff]') for i, m in zip(bits, mask_str))
```

2024-10-07 20:41 UTC, averne commented
> Is your `applypattern-ghidra.py` script able to handle these as well?

Yes, as far as I understand (didn't look too deep), it's because the py3 produces a bytestring vs a normal string with py2, with has to get escaped (so with a lot more backward slashes)

2024-10-07 20:42 UTC, averne commented on pattern/makepattern.py
>  			positions = [m.start() for m in re.finditer(regex, textstr)]
Thanks for the suggestion, I didn't realize you were trying to keep those scripts compatible with python2.

2024-10-07 20:43 UTC, TSRBerry commented on pattern/makepattern.py
>  			positions = [m.start() for m in re.finditer(regex, textstr)]
Just in case SciresM modifies his version of these again or wants to use this one. :D

2024-10-07 20:46 UTC, TSRBerry approved these changes
Lgtm now! Thank you again! :D

2024-10-07 20:47 UTC, merged